## one-hot-encoding is used when your data is categorial and nominal

In [2]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('cars.csv')
df.sample(15)

        brand  km_driven    fuel         owner  selling_price
5500     Ford      60000  Diesel   First Owner         225000
2245  Hyundai      50000  Petrol  Second Owner         130000
1584   Maruti      20000  Petrol   First Owner         575000
3254   Maruti      22947  Petrol   First Owner         500000
1570   Nissan      11533  Petrol   First Owner         950000
1157     Tata     175000  Diesel  Second Owner         200000
5931     Tata      20000  Petrol   First Owner         500000
215    Maruti      60000  Petrol   First Owner         290000
1402   Maruti      52000  Diesel   First Owner         800000
4237     Tata     110000  Diesel   First Owner         503000
2535    Honda      40000  Diesel   First Owner         825000
2632   Jaguar      45000  Diesel   First Owner        3200000
7989  Hyundai      50000  Petrol   First Owner         470000
2412   Maruti      90000  Petrol  Second Owner          50000
7023  Hyundai      51856  Petrol   Third Owner         320000

## here the BRAND and FUEL does not represent any order therefore both are the nominal categorical columns

In [4]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# One_hot_encoding - using the pandas form  using the get_dummies

In [5]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## but you always required to remove the first column for removing the multicolleaniarity problem 
## so you remove the first column from each new created columns

# k-1 onehotencoding

In [6]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# but in machine learning you cannot use the pandas because it does not remeber the new genrated columns properly

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [9]:
x_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

## onehotencoding using the sklearn

In [11]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [18]:
x_train_new = ohe.transform(x_train[['fuel','owner']])
x_test_new = ohe.transform(x_test[['fuel','owner']])

In [19]:

x_train_new.shape

(6502, 7)

## now adding all the splited columns at one place

In [20]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

# OneHotEncoding with Top Categories

In [22]:
counts = df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

## now we cannot create the seprate columns for all it slows our speed theare for we take the individual columns for all the TOP COMPANIES and which having the value more than 100 and remaining should be noted as the OTHERS

In [23]:
df['brand'].nunique()
threshold = 100

In [24]:
repl = counts[counts <= threshold].index

In [25]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
6877,False,False,False,False,False,False,False,True,False,False,False,False,False
7254,False,False,False,False,False,False,False,False,False,True,False,False,False
3745,False,False,False,False,False,False,True,False,False,False,False,False,False
5929,False,False,False,True,False,False,False,False,False,False,False,False,False
4377,False,False,False,False,False,False,False,False,False,False,False,False,True